using System;
using System.Collections.Generic;

namespace Usa.chili.Domain
{
    public partial class Jay224
    {
        public DateTime Ts { get; set; }
        public int? RecId { get; set; }
        public short? TableCode { get; set; }
        public short? Year { get; set; }
        public byte? Month { get; set; }
        public byte? DayOfMon { get; set; }
        public short? DayOfYear { get; set; }
        public byte? Hour { get; set; }
        public byte? Minute { get; set; }
        public short? StationId { get; set; }
        public double? Lat { get; set; }
        public double? Lon { get; set; }
        public double? Elev { get; set; }
        public double? Sign { get; set; }
        public double? BattMax { get; set; }
        public double? BattMin { get; set; }
        public byte? DoorOpen1 { get; set; }
        public double? Batt { get; set; }
        public double? ErrorWtch { get; set; }
        public double? ErrorOver { get; set; }
        public double? ErrorVolt { get; set; }
        public double? Lithium { get; set; }
        public double? ErrorFlsh { get; set; }
        public int? ObsInSummTot { get; set; }
        public double? PrecipTb3Tot { get; set; }
        public double? PrecipTxTot { get; set; }
        public double? PrecipTb3Today { get; set; }
        public double? PrecipTxToday { get; set; }
        public double? Ptemp { get; set; }
        public double? IrtsTrgt { get; set; }
        public double? IrtsBody { get; set; }
        public double? SoilSfcT { get; set; }
        public double? SoilT5cm { get; set; }
        public double? SoilT10cm { get; set; }
        public double? SoilT20cm { get; set; }
        public double? SoilT50cm { get; set; }
        public double? SoilT100cm { get; set; }
        public double? AirT1pt5m { get; set; }
        public double? AirT2m { get; set; }
        public double? AirT9pt5m { get; set; }
        public double? AirT10m { get; set; }
        public double? Rh2m { get; set; }
        public double? Rh10m { get; set; }
        public double? Pressure1 { get; set; }
        public double? Pressure2 { get; set; }
        public double? TotalRadn { get; set; }
        public double? QuantRadn { get; set; }
        public double? WndDir2m { get; set; }
        public double? WndDir10m { get; set; }
        public double? WndSpd2m { get; set; }
        public double? WndSpd10m { get; set; }
        public double? WndSpdVert { get; set; }
        public double? Vitel5cmA { get; set; }
        public double? Vitel5cmB { get; set; }
        public double? Vitel5cmC { get; set; }
        public double? Vitel5cmD { get; set; }
        public double? Vitel10cmA { get; set; }
        public double? Vitel10cmB { get; set; }
        public double? Vitel10cmC { get; set; }
        public double? Vitel10cmD { get; set; }
        public double? Vitel20cmA { get; set; }
        public double? Vitel20cmB { get; set; }
        public double? Vitel20cmC { get; set; }
        public double? Vitel20cmD { get; set; }
        public double? Vitel50cmA { get; set; }
        public double? Vitel50cmB { get; set; }
        public double? Vitel50cmC { get; set; }
        public double? Vitel50cmD { get; set; }
        public double? Vitel100cmA { get; set; }
        public double? Vitel100cmB { get; set; }
        public double? Vitel100cmC { get; set; }
        public double? Vitel100cmD { get; set; }
        public double? PtempTot { get; set; }
        public double? IrtsTrgtTot { get; set; }
        public double? IrtsBodyTot { get; set; }
        public double? SoilSfcTTot { get; set; }
        public double? SoilT5cmTot { get; set; }
        public double? SoilT10cmTot { get; set; }
        public double? SoilT20cmTot { get; set; }
        public double? SoilT50cmTot { get; set; }
        public double? SoilT100cmTot { get; set; }
        public double? AirT1pt5mTot { get; set; }
        public double? AirT2mTot { get; set; }
        public double? AirT9pt5mTot { get; set; }
        public double? AirT10mTot { get; set; }
        public double? Rh2mTot { get; set; }
        public double? Rh10mTot { get; set; }
        public double? PressureTot1 { get; set; }
        public double? PressureTot2 { get; set; }
        public double? TotalRadnTot { get; set; }
        public double? QuantRadnTot { get; set; }
        public double? WndDir2mTot { get; set; }
        public double? WndDir10mTot { get; set; }
        public double? WndSpd2mTot { get; set; }
        public double? WndSpd10mTot { get; set; }
        public double? WndSpdVertTot { get; set; }
        public double? PtempMax { get; set; }
        public DateTime? PtempTmx { get; set; }
        public double? IrtsTrgtMax { get; set; }
        public double? IrtsBodyMax { get; set; }
        public DateTime? IrtsTrgtTmx { get; set; }
        public DateTime? IrtsBodyTmx { get; set; }
        public double? SoilSfcTMax { get; set; }
        public DateTime? SoilSfcTTmx { get; set; }
        public double? SoilT5cmMax { get; set; }
        public double? SoilT10cmMax { get; set; }
        public double? SoilT20cmMax { get; set; }
        public double? SoilT50cmMax { get; set; }
        public double? SoilT100cmMax { get; set; }
        public DateTime? SoilT5cmTmx { get; set; }
        public DateTime? SoilT10cmTmx { get; set; }
        public DateTime? SoilT20cmTmx { get; set; }
        public DateTime? SoilT50cmTmx { get; set; }
        public DateTime? SoilT100cmTmx { get; set; }
        public double? AirT1pt5mMax { get; set; }
        public DateTime? AirT1pt5mTmx { get; set; }
        public double? AirT2mMax { get; set; }
        public DateTime? AirT2mTmx { get; set; }
        public double? AirT9pt5mMax { get; set; }
        public DateTime? AirT9pt5mTmx { get; set; }
        public double? AirT10mMax { get; set; }
        public DateTime? AirT10mTmx { get; set; }
        public double? Rh2mMax { get; set; }
        public double? Rh10mMax { get; set; }
        public DateTime? Rh2mTmx { get; set; }
        public DateTime? Rh10mTmx { get; set; }
        public double? PressureMax1 { get; set; }
        public double? PressureMax2 { get; set; }
        public DateTime? PressureTmx1 { get; set; }
        public DateTime? PressureTmx2 { get; set; }
        public double? TotalRadnMax { get; set; }
        public DateTime? TotalRadnTmx { get; set; }
        public double? QuantRadnMax { get; set; }
        public DateTime? QuantRadnTmx { get; set; }
        public double? WndDir2mMax { get; set; }
        public double? WndDir10mMax { get; set; }
        public DateTime? WndDir2mTmx { get; set; }
        public DateTime? WndDir10mTmx { get; set; }
        public double? WndSpd2mMax { get; set; }
        public double? WndSpd10mMax { get; set; }
        public DateTime? WndSpd2mTmx { get; set; }
        public DateTime? WndSpd10mTmx { get; set; }
        public double? WndSpdVertMax { get; set; }
        public DateTime? WndSpdVertTmx { get; set; }
        public double? PtempMin { get; set; }
        public DateTime? PtempTmn { get; set; }
        public double? IrtsTrgtMin { get; set; }
        public double? IrtsBodyMin { get; set; }
        public DateTime? IrtsTrgtTmn { get; set; }
        public DateTime? IrtsBodyTmn { get; set; }
        public double? SoilSfcTMin { get; set; }
        public DateTime? SoilSfcTTmn { get; set; }
        public double? SoilT5cmMin { get; set; }
        public double? SoilT10cmMin { get; set; }
        public double? SoilT20cmMin { get; set; }
        public double? SoilT50cmMin { get; set; }
        public double? SoilT100cmMin { get; set; }
        public DateTime? SoilT5cmTmn { get; set; }
        public DateTime? SoilT10cmTmn { get; set; }
        public DateTime? SoilT20cmTmn { get; set; }
        public DateTime? SoilT50cmTmn { get; set; }
        public DateTime? SoilT100cmTmn { get; set; }
        public double? AirT1pt5mMin { get; set; }
        public DateTime? AirT1pt5mTmn { get; set; }
        public double? AirT2mMin { get; set; }
        public DateTime? AirT2mTmn { get; set; }
        public double? AirT9pt5mMin { get; set; }
        public DateTime? AirT9pt5mTmn { get; set; }
        public double? AirT10mMin { get; set; }
        public DateTime? AirT10mTmn { get; set; }
        public double? Rh2mMin { get; set; }
        public double? Rh10mMin { get; set; }
        public DateTime? Rh2mTmn { get; set; }
        public DateTime? Rh10mTmn { get; set; }
        public double? PressureMin1 { get; set; }
        public double? PressureMin2 { get; set; }
        public DateTime? PressureTmn1 { get; set; }
        public DateTime? PressureTmn2 { get; set; }
        public double? TotalRadnMin { get; set; }
        public DateTime? TotalRadnTmn { get; set; }
        public double? QuantRadnMin { get; set; }
        public DateTime? QuantRadnTmn { get; set; }
        public double? WndDir2mMin { get; set; }
        public double? WndDir10mMin { get; set; }
        public DateTime? WndDir2mTmn { get; set; }
        public DateTime? WndDir10mTmn { get; set; }
        public double? WndSpd2mMin { get; set; }
        public double? WndSpd10mMin { get; set; }
        public DateTime? WndSpd2mTmn { get; set; }
        public DateTime? WndSpd10mTmn { get; set; }
        public double? WndSpdVertMin { get; set; }
        public DateTime? WndSpdVertTmn { get; set; }
        public double? WndSpd2mWvc1 { get; set; }
        public double? WndSpd2mWvc2 { get; set; }
        public double? WndSpd2mWvc3 { get; set; }
        public double? WndSpd2mWvc4 { get; set; }
        public double? WndSpd10mWvc1 { get; set; }
        public double? WndSpd10mWvc2 { get; set; }
        public double? WndSpd10mWvc3 { get; set; }
        public double? WndSpd10mWvc4 { get; set; }
        public double? WndSpd2mStd { get; set; }
        public double? WndSpd10mStd { get; set; }
    }
}
