namespace Usa.chili.Common
{
    public enum VariableEnum
    {
        Precip_TB3_Tot,
        Precip_TX_Tot,
        Precip_TB3_Today,
        Precip_TX_Today,
        SoilSfcT,
        SoilT_5cm,
        SoilT_10cm,
        SoilT_20cm,
        SoilT_50cm,
        SoilT_100cm,
        Temp_C,
        AirT_1pt5m,
        AirT_2m,
        AirT_9pt5m,
        AirT_10m,
        SoilCond_tc,
        SoilWaCond_tc,
        wfv,
        RH_2m,
        RH_10m,
        Pressure_1,
        Pressure_2,
        TotalRadn,
        QuantRadn,
        WndDir_2m,
        WndDir_10m,
        WndSpd_2m,
        WndSpd_10m,
        WndSpd_Vert,
        WndSpd_2m_Max,
        WndSpd_10m_Max,
        Batt,
        Door
    }
}